# Site settings
title: Liquid Collection Home
description: >- # this means to ignore newlines until "baseurl:"
  Layout that builds collection page list
url: 'https://liquid-utilities.github.io'
author: S0AndS0


# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-github-metadata


repository: liquid-utilities/collection-home


## Thanks be to - https://jekyllrb.com/docs/collections/
collections_dir: documentation
collections:
  example-collection:
    output: true
    permalink: /:collection/:name/


## Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
